[package]
name = "ember-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ember"
path = "src/main.rs"

[dependencies]
ember-span = { path = "../ember-span" }
ember-diag = { path = "../ember-diag" }
ember-lexer = { path = "../ember-lexer" }
ember-ast = { path = "../ember-ast" }
ember-parser = { path = "../ember-parser" }
ember-resolve = { path = "../ember-resolve" }
ember-types = { path = "../ember-types" }
ember-tree = { path = "../ember-tree" }
ember-bytecode = { path = "../ember-bytecode" }
ember-compile = { path = "../ember-compile" }
ember-vm = { path = "../ember-vm" }
ember-fmt = { path = "../ember-fmt" }
clap = { version = "4", features = ["derive"] }

[features]
gc-stress = ["ember-vm/gc-stress"]
gc-log = ["ember-vm/gc-log"]
