[package]
name = "ember-vm"
version.workspace = true
edition.workspace = true

[dependencies]
ember-span = { path = "../ember-span" }
ember-diag = { path = "../ember-diag" }
ember-ast = { path = "../ember-ast" }
ember-bytecode = { path = "../ember-bytecode" }
rustc-hash = "2"

[dev-dependencies]
ember-parser = { path = "../ember-parser" }
ember-resolve = { path = "../ember-resolve" }
ember-compile = { path = "../ember-compile" }
